name: api
description: API Gateway with Lambda backend
portfolio: application-services

parameters:
  VpcId:
    type: String
    description: VPC for Lambda
    required: true

  SubnetIds:
    type: CommaDelimitedList
    description: Subnets for Lambda
    required: true

  DbEndpoint:
    type: String
    description: Database endpoint
    required: true

  DbPort:
    type: String
    description: Database port
    required: true

  DbSecretArn:
    type: String
    description: Database credentials secret ARN
    required: true

outputs:
  ApiEndpoint:
    description: API Gateway endpoint URL
    export: true

  ApiKey:
    description: API key for authentication
    export: true
