name: Product Change
description: Modify an existing product capability
title: "[CHANGE] "
labels: ["change", "product"]
body:
  - type: markdown
    attributes:
      value: |
        ## Product Change Request
        This template is for modifying existing product capabilities.

  - type: dropdown
    id: product
    attributes:
      label: Product
      description: Which product needs to be changed?
      options:
        - networking
        - database
        - api
    validations:
      required: true

  - type: dropdown
    id: change-type
    attributes:
      label: Change Type
      description: What type of change is this?
      options:
        - Enhancement - Improve existing capability
        - Configuration - Change parameters/settings
        - Dependency - Update dependencies
        - Security - Security improvement
        - Performance - Performance optimization
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: How does the product currently work?
      placeholder: Describe the current state that needs to change
    validations:
      required: true

  - type: textarea
    id: desired-behavior
    attributes:
      label: Desired Behavior
      description: How should the product work after this change?
      placeholder: Describe the expected outcome
    validations:
      required: true

  - type: textarea
    id: impact-analysis
    attributes:
      label: Impact Analysis
      description: What might be affected by this change?
      placeholder: |
        - Dependent products:
        - Existing deployments:
        - Breaking changes:

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How do we verify the change is successful?
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] CAPABILITY.md updated
        - [ ] Tests updated
    validations:
      required: true
