# Implementer Skill
# Implements CloudFormation template changes

name: implementer
description: |
  Implements the technical changes defined in work orders.
  Modifies CloudFormation templates, product.yaml configs, and
  coordinates with capability-writer and test-writer.
  Can operate as a sub-agent within a lane managed by orchestrator.

trigger:
  type: routed
  from: orchestrator | work-order-planner
  input: work_orders

context:
  required:
    - work_orders
    - branch_name
    - product_templates  # Current template.yaml files
    - product_configs  # Current product.yaml files
  lane_context:  # When operating under orchestrator
    - lane_id
    - phase_id
    - orchestrator_callback
  optional:
    - reference_templates  # Examples from other products
    - outputs_from_dependencies  # Outputs from completed dependent lanes

behavior:
  implementation:
    for_each: work_order
    where: type in [template, config]
    
    steps:
      1_analyze:
        action: understand_current_state
        read:
          - "products/{product}/template.yaml"
          - "products/{product}/product.yaml"
          - "products/{product}/CAPABILITY.md"
      
      2_plan_changes:
        determine:
          - resources_to_add
          - resources_to_modify
          - parameters_to_add
          - outputs_to_add
          - iam_permissions_needed
      
      3_implement:
        actions:
          - modify_template
          - update_product_config
          - validate_changes
        
        validation:
          - cfn-lint on template.yaml
          - yaml syntax check
          - dependency consistency check
      
      4_commit:
        action: git_commit
        message: "{work_order_type}: {work_order_title}"
        scope: only_changed_files

  best_practices:
    cloudformation:
      - Use parameters for configurable values
      - Add descriptions to all parameters and outputs
      - Use !Ref and !GetAtt for resource references
      - Follow naming convention: {Product}{ResourceType}
      - Add appropriate tags to all resources
      - Use conditions for environment-specific resources
    
    security:
      - No hardcoded secrets
      - Least-privilege IAM policies
      - Encryption at rest for data stores
      - No public access unless explicitly required
      - Security groups with minimal required ports
    
    outputs:
      - Export all values needed by dependent products
      - Use consistent naming: {ResourceType}Id, {ResourceType}Arn

  coordination:
    after_template_changes:
      trigger:
        - capability-writer
        - test-writer
    
    report_to_orchestrator:
      # When operating as sub-agent in a lane
      events:
        - work_order_started: {wo_id, timestamp}
        - work_order_complete: {wo_id, outputs, commit_sha}
        - lane_blocked: {wo_id, reason, dependency_needed}
        - lane_error: {wo_id, error_details}

  sub_agent_mode:
    # Behavior when operating under orchestrator control
    isolation:
      - Work only on assigned lane branch
      - Do not modify files outside assigned products
      - Report all progress to orchestrator
    
    dependency_handling:
      when_dependency_not_available:
        action: report_blocked
        wait_for: orchestrator_provides_dependency
      
      when_dependency_provided:
        action: resume_work_order
        use: provided_outputs

outputs:
  - modified_files: list of changed files
  - commit_sha: git commit hash
  - validation_results: cfn-lint output
  - produced_outputs: outputs that dependent lanes may need

transitions:
  - to: capability-writer
    when: template_changes_complete
    pass: modified_files, work_orders
  - to: self
    when: more_work_orders_to_implement
  - to: orchestrator (callback)
    when: lane_work_complete
    pass: lane_results
