# Requirement Shaper Skill
# Conversational refinement of business requirements

name: requirement-shaper
description: |
  Engages in conversation with the human to understand, clarify, and shape
  business requirements into actionable specifications. Does not proceed
  until human explicitly confirms the requirement.

trigger:
  type: routed
  from: guide
  intent: new_requirement

context:
  required:
    - human_input  # Initial requirement statement
    - existing_products  # Current product catalog
    - product_capabilities  # CAPABILITY.md contents
  optional:
    - related_requirements  # Previous similar requirements

behavior:
  conversation_flow:
    1_understand:
      action: parse_initial_requirement
      extract:
        - affected_products
        - capability_type  # new feature, enhancement, fix
        - business_value
        - technical_hints
    
    2_clarify:
      action: ask_clarifying_questions
      question_categories:
        scope:
          - "Which users/systems will use this?"
          - "Is this for all environments or specific ones?"
        behavior:
          - "What should happen when...?"
          - "How should errors be handled?"
        integration:
          - "Does this need to interact with other products?"
          - "Are there external systems involved?"
        constraints:
          - "Are there performance requirements?"
          - "Any security considerations?"
      rules:
        - Ask maximum 3-4 questions at a time
        - Group related questions together
        - Skip questions already answered in initial input
    
    3_summarize:
      action: present_summary
      format: |
        **Requirement: {title}**
        
        **Business Value:** {why}
        
        **Scope:**
        - Affected products: {products}
        - Users/consumers: {users}
        
        **Behavior:**
        {behavior_description}
        
        **Constraints:**
        {constraints}
        
        Is this correct? Should I proceed to create work orders?
    
    4_confirm:
      wait_for: explicit_confirmation
      accepted_responses:
        - "yes"
        - "proceed"
        - "correct"
        - "approved"
        - "go ahead"
      on_modification:
        action: return_to_clarify
      on_confirmation:
        action: transition_to_work_order_planner

  guardrails:
    - Never assume - always ask if unclear
    - Don't create work orders without confirmation
    - Keep conversation focused on the requirement
    - Reference existing CAPABILITY.md to show current state

outputs:
  - shaped_requirement:
      title: string
      description: string
      affected_products: list
      acceptance_criteria: list
      constraints: list
  - conversation_summary: string

transitions:
  - to: work-order-planner
    when: human_confirms_requirement
    pass: shaped_requirement
  - to: self
    when: human_provides_clarification
  - to: guide
    when: human_cancels
