# AWS profiles configuration
# Shared between bootstrap.yaml and catalog.yaml
#
# Environment promotion: dev -> stage -> prod
# - dev:   Development testing, auto-deploy on merge to develop
# - stage: Pre-production validation, auto-deploy on merge to main
# - prod:  Production, manual approval required

profiles:
  dev:
    aws_profile: my-aws-dev
    aws_region: eu-west-1
    account_id: "111111111111"

  stage:
    aws_profile: my-aws-stage
    aws_region: eu-west-1
    account_id: "333333333333"

  prod:
    aws_profile: my-aws-prod
    aws_region: eu-west-1
    account_id: "222222222222"
