AWSTemplateFormatVersion: '2010-09-09'
Description: RDS PostgreSQL database

Parameters:
  Environment:
    Type: String
    Default: dev

  VpcId:
    Type: String

  SubnetIds:
    Type: CommaDelimitedList

  SecurityGroupId:
    Type: String

  InstanceClass:
    Type: String
    Default: db.t3.micro

  DatabaseName:
    Type: String
    Default: appdb

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS
      SubnetIds: !Ref SubnetIds
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-db-subnet-group"

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for RDS
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref SecurityGroupId
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-db-sg"

  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${Environment}-db-credentials"
      Description: RDS database credentials
      GenerateSecretString:
        SecretStringTemplate: '{"username": "dbadmin"}'
        GenerateStringKey: password
        PasswordLength: 32
        ExcludeCharacters: '"@/\'

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub "${Environment}-postgres"
      DBInstanceClass: !Ref InstanceClass
      Engine: postgres
      EngineVersion: "15.4"
      DBName: !Ref DatabaseName
      MasterUsername: !Sub "{{resolve:secretsmanager:${DBSecret}:SecretString:username}}"
      MasterUserPassword: !Sub "{{resolve:secretsmanager:${DBSecret}:SecretString:password}}"
      AllocatedStorage: 20
      StorageType: gp3
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
      PubliclyAccessible: false
      MultiAZ: false
      DeletionProtection: false
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-postgres"

  SecretAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref DBSecret
      TargetId: !Ref DBInstance
      TargetType: AWS::RDS::DBInstance

Outputs:
  DatabaseEndpoint:
    Description: RDS endpoint
    Value: !GetAtt DBInstance.Endpoint.Address
    Export:
      Name: !Sub "${Environment}-DatabaseEndpoint"

  DatabasePort:
    Description: RDS port
    Value: !GetAtt DBInstance.Endpoint.Port
    Export:
      Name: !Sub "${Environment}-DatabasePort"

  DatabaseSecretArn:
    Description: Secrets Manager ARN
    Value: !Ref DBSecret
    Export:
      Name: !Sub "${Environment}-DatabaseSecretArn"
