name: networking
description: VPC and networking infrastructure
portfolio: infrastructure

parameters:
  Environment:
    type: String
    description: Environment name
    default: dev
    required: true

  VpcCidr:
    type: String
    description: CIDR block for VPC
    default: "10.0.0.0/16"
    required: true

outputs:
  VpcId:
    description: VPC identifier
    export: true

  PublicSubnetIds:
    description: Comma-separated public subnet IDs
    export: true

  PrivateSubnetIds:
    description: Comma-separated private subnet IDs
    export: true

  SecurityGroupId:
    description: Default security group ID
    export: true
